# Generated by Django 4.1.7 on 2023-04-25 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="principalabout",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="principalUpload"
                    ),
                ),
                ("fname", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=30)),
                ("cname", models.CharField(max_length=30)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("dob", models.DateField(max_length=8)),
                ("qualification", models.CharField(max_length=10)),
                ("from1", models.DateField(max_length=8)),
                ("to", models.DateField(max_length=8)),
                ("join", models.DateField(max_length=8)),
                ("seperate", models.DateField(max_length=8)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="polls.principal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schoolabout",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("publish", models.DateField(blank=True, null=True)),
                (
                    "principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schoolss",
                        to="polls.principal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Principalabouts",
            fields=[
                ("cname", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=10)),
                ("from1", models.DateField(max_length=8)),
                ("to", models.DateField(max_length=8)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="principalabouts",
                        to="principal.principalabout",
                    ),
                ),
            ],
        ),
    ]
